[common]
platform = atmelsam
board = mkrwan1310
framework = arduino
lib_deps =
    sandeepmistry/LoRa

[env:S1]
extends = common
build_src_filter = +<S1/>
build_flags =
    -D NODE_ADDR=0x10

[env:W1]
extends = common
build_src_filter = +<W1/>
build_flags =
    -D NODE_ADDR=0x01

[env:W2]
extends = common
build_src_filter = +<W1/>
build_flags =
    -D NODE_ADDR=0x02

[env:W3]
extends = common
build_src_filter = +<W1/>
build_flags =
    -D NODE_ADDR=0x03

[env:W4]
extends = common
build_src_filter = +<W1/>
build_flags =
    -D NODE_ADDR=0x04

[env:W5]
extends = common
build_src_filter = +<W1/>
build_flags =
    -D NODE_ADDR=0x05

[env:W0]
extends = common
build_src_filter = +<W0/>

[env:Snippet-Serial]
extends = common
build_src_filter = +<_snippets/Serial/>

[env:Snippet-WireMaster]
extends = common
build_src_filter = +<_snippets/WireMaster/>

[env:Snippet-WireSlave]
extends = common
build_src_filter = +<_snippets/WireSlave/>